### ISSUE TITLE
Add multiple bindings...

### ISSUE THREAD

**Issue by jdinh-mackevision** [inversify/inversify-binding-decorators#53]
Is there anyway to bind multiple decorators to a class? Also, would bindings be singleton providers or instances?

**Comment by remojansen** [comment]
You can use both the `inversify-binding-decorators` API and the container API together so if you need to bind a class to two interfaces you can always use the container API:

```ts
container.bind<SomeInterface>("SomeInterface").to(SomeClass);
container.bind<SomeInterface>("SomeOtherInterface").to(SomeClass);
```

I assume that this only happens with a few of your classes so it shouldn't be too painful to do just for a few classes.

Also, I'm not sure because I haven't tried it but maybe the following works:

```ts
@provide("SomeInterface")
@provide("SomeOtherInterface")
class SomeClass {
    // ....
}
```

Please create issues in [the main repo](https://github.com/inversify/InversifyJS/issues).

**Comment by knjname** [comment]
Currently, multiple `@provide("...")` don't work because of `Cannot apply @injectable decorator multiple times.` error.

**Comment by remojansen** [comment]
I have created an issue to fix this: https://github.com/inversify/InversifyJS/issues/674
